services:
  # Backend API Web Service
  - type: web
    name: financy-api
    runtime: node
    plan: free
    region: singapore
    rootDir: Backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres.ktwlxmhavcvihlwvnnmg:Anni%40123%23%2A%24@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        value: supersecretjwt-financy-prod-2026
      - key: CORS_ORIGIN
        value: "*"
