"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const reportController_1 = require("../controllers/reportController");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
router.use(auth_1.authenticateToken);
router.get("/top-spending", reportController_1.getTopSpending);
router.get("/daily-spending", reportController_1.getDailySpending);
exports.default = router;
